/**
 * The ML Sidecar app icon as an inline SVG — same geometry as the iOS icon
 * generated by tools/make_icon.swift (phone + sparkle + broadcast arcs on a
 * navy tile with the indigo→cyan gradient).
 */
export function SidecarLogo({ size = 28, tile = true }: { size?: number; tile?: boolean }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 1024 1024"
      role="img"
      aria-label="ML Sidecar"
    >
      <defs>
        <linearGradient id="sidecar-g" gradientUnits="userSpaceOnUse" x1="200" y1="844" x2="900" y2="84">
          <stop offset="0" stopColor="#4f46e5" />
          <stop offset="1" stopColor="#22d3ee" />
        </linearGradient>
      </defs>

      {tile && <rect width="1024" height="1024" rx="228" fill="#0b1020" />}

      {/* Phone body */}
      <rect
        x="268" y="240" width="330" height="552" rx="76"
        fill="none" stroke="url(#sidecar-g)" strokeWidth="44"
      />
      {/* Home indicator */}
      <line
        x1="380" y1="718" x2="486" y2="718"
        stroke="url(#sidecar-g)" strokeWidth="30" strokeLinecap="round"
      />
      {/* AI sparkle on the screen */}
      <path
        fill="url(#sidecar-g)"
        d="M433 368 L457 440 L529 464 L457 488 L433 560 L409 488 L337 464 L409 440 Z"
      />
      {/* Broadcast arcs from the top-right corner */}
      <g fill="none" stroke="url(#sidecar-g)" strokeWidth="44" strokeLinecap="round">
        <path d="M756.2 331.4 A118 118 0 0 0 707.4 171.8" />
        <path d="M828.6 369.9 A200 200 0 0 0 745.9 99.4" />
        <path d="M901 408.4 A282 282 0 0 0 784.4 27" />
      </g>
      <circle cx="652" cy="276" r="30" fill="url(#sidecar-g)" />
    </svg>
  );
}
